### ISSUE TITLE
Unable to run the example project.

### ISSUE THREAD

**Issue by pbandyop** [wallnerryan/floodlight#1]
Hello,

so I am trying out the Floodlight and I am able to successfully install and run it with the command:

`java -jar target/floodlight.jar`

Now, I am trying to run the example projects given in the repository (https://github.com/floodlight/floodlight/tree/master/example) but I am unable to do it. 

Basically what I did is, I started floodlight in one terminal and in another terminal I went to the directory which has the example project and ran the following command:

```
$ cd ../floodlight/example
$ ./graphTopo.py 192.168.1.100 6642
```
but unfortunately, I am getting the following error:

```
Connecting to 192.168.1.100:6642 ...Traceback (most recent call last):

  File "./graphTopo.py", line 44, in <module> 

    links = simple_json_get(URL) 

  File "./graphTopo.py", line 9, in simple_json_get 

    return json.loads(urllib2.urlopen(url).read()) 

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen 

    return opener.open(url, data, timeout) 

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open 

    response = self._open(req, data) 

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open 

    '_open', req) 

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain 

    result = func(*args) 

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open 

    return self.do_open(httplib.HTTPConnection, req) 

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open 

    raise URLError(err) 

urllib2.URLError: <urlopen error [Errno 60] Operation timed out>
```

What I am doing wrong? How can I get the examples running? Any help will be appreciated.

**Comment by navjotbans** [comment]
Hey have you figured out what was wrong 
I too have same issues
